In [2]:
#Convention for importing numpy
import numpy as np

In [3]:
arr = [6,7,8,9]
print(type(arr)) # prints <class 'list'>

<class 'list'>


In [4]:
np_arr = np.array(arr)
print(type(np_arr)) # prints <class 'numpy.ndarray'>
print(np_arr.shape) # prints (4,) - np_arr is a 1d array with 4 items
print(np_arr.dtype) # prints int64

#get the dimension of np_arr with ndim
print(np_arr.ndim) # prints 1

<class 'numpy.ndarray'>
(4,)
int64
1


In [6]:
b = np.array([[1,2,3], [4,5,6]])
print(b) # prints [[1 2 3]
         #        [ 4 5 6]]
print(b.ndim) # prints 2
b.shape       # prints(2, 3) - b a 2d array with 2 rows and 3 columns

[[1 2 3]
 [4 5 6]]
2


(2, 3)

Built-in functions to initialise numpy 

In [9]:
# # 2 x 3 array with random values
# np.random.random((2,3)) = array([[0.60793904, 0.02881965, 0.73022145], [0.34183628, 0.63274057, 0.07945224]])
np.random.random((2,3))

array([[0.9116914 , 0.0822941 , 0.56795337],
       [0.54807701, 0.63439325, 0.6257343 ]])

In [11]:
# 2 x 3 array of zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# a 2 x 3 array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# 3 x 3 identity matrix
np.zeros(3)

array([0., 0., 0.])

Intra-operability of Arrays and Scalars.

Vectorisation in numpy arrays allows for faster processing by eliminating for loops when dealing with arrays of equal shape. This allows for batch arithmetic operations on the arrays by applying the operator elementwise. Similarly, scalars are also propagated element-wise across an array. For arrays with different sizes, it is impossible to perform element-wise operations instead; numpy handles this by broadcasting provided the dimensions of the arrays are the same or, one of the dimensions of the array is 1.

In [14]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

In [15]:
c + d


array([[13., 13., 13.],
       [10., 10., 10.]])

In [16]:
c * d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

Indexing With Arrays & Using Arrays for Data Processing

The elements in the example arrays above can be accessed by indexing like lists in Python such that:

In [19]:
np_arr[0] = 6
np_arr[3] = 9
b[0,0] = 1 # row 0, column 0 = 1
b[1,2] = 6 # row 1, column 2 = 6
c[0,1] = 8 # row 0, column 1 = 8

In [20]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
c

array([[9., 8., 7.],
       [1., 2., 3.]])

Elements in arrays  can also be retrieved by slicing rows and columns or a combination of indexing and slicing.

In [23]:
d[1, 0:2]

array([9., 8.])

In [24]:
e = np.array([[10, 11, 12], [13, 14,15], [16, 17, 18], [19, 20, 21]])

In [25]:
e

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [26]:
e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

Advanced indexing 

In [29]:
# integer indexing 
e[e>15] # elements of e greater than 15

array([16, 17, 18, 19, 20, 21])

Numpy also has inbuilt mathematical functions like sum(), mean(), std(), corrcoef(), min() and others. 
It interestingly allows for comparing arrays using == to check if two arrays have the same elements,  elements in 
the first array are greater than or less than those of the second array using  > and  <.

File Input and Output With Arrays
Numpy arrays can be loaded from and saved to binary files with .npy as the extension using load() and save() 
respectively. This can also be done with text files with text files using loadtxt() and savetxt().